name: Build APK

on:
  workflow_dispatch: # Allows you to manually trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemGovorov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          repository_root: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToDo-App-APK
          path: ${{ steps.buildozer.outputs.filename }}
